"""add agent character table

Revision ID: 9a75083c5ba6
Revises: c869e4b5c85f
Create Date: 2025-08-29 15:23:06.845055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a75083c5ba6'
down_revision: Union[str, Sequence[str], None] = 'c869e4b5c85f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='buddy'
    )
    op.create_index(op.f('ix_buddy_agent_character_id'), 'agent_character', ['id'], unique=False, schema='buddy')
    op.create_table('agent_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(), nullable=False),
    sa.Column('chat_content', sa.JSON(), nullable=False),
    sa.Column('character', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='buddy'
    )
    op.create_index(op.f('ix_buddy_agent_chat_account'), 'agent_chat', ['account'], unique=True, schema='buddy')
    op.create_index(op.f('ix_buddy_agent_chat_id'), 'agent_chat', ['id'], unique=False, schema='buddy')
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Double(), nullable=False),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('amount'),
    schema='buddy'
    )
    op.create_index(op.f('ix_buddy_transactions_id'), 'transactions', ['id'], unique=False, schema='buddy')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('agent_transaction_limit', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account'),
    schema='buddy'
    )
    op.create_index(op.f('ix_buddy_users_id'), 'users', ['id'], unique=False, schema='buddy')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buddy_users_id'), table_name='users', schema='buddy')
    op.drop_table('users', schema='buddy')
    op.drop_index(op.f('ix_buddy_transactions_id'), table_name='transactions', schema='buddy')
    op.drop_table('transactions', schema='buddy')
    op.drop_index(op.f('ix_buddy_agent_chat_id'), table_name='agent_chat', schema='buddy')
    op.drop_index(op.f('ix_buddy_agent_chat_account'), table_name='agent_chat', schema='buddy')
    op.drop_table('agent_chat', schema='buddy')
    op.drop_index(op.f('ix_buddy_agent_character_id'), table_name='agent_character', schema='buddy')
    op.drop_table('agent_character', schema='buddy')
    # ### end Alembic commands ###
